version: "3"
services:
  grafana:
    container_name: grafana
    build:
      context: ./env/grafana/
      dockerfile: grafana
    ports:
      - 60801:3000
    volumes:
      - ./data/grafana/grafana-data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  iobroker:
    container_name: iobroker
    build:
      context: ./env/iobroker/
      dockerfile: iobroker
    ports:
      - 60802:8081
      - 60803:60803
      - 1883:1883
    volumes:
      - ./data/iobroker/opt/:/opt/iobroker/
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_NAME}
      - INFLUXDB_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ADMIN_ENABLED=${INFLUXDB_ROOT_USER_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

